on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v1_local
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v1_public
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v2_local
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v2_public
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v3_local
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v3_public
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v4_local
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features v4_public
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-audit
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
